### ISSUE TITLE
Use petgraph crate for Graph operations

### ISSUE THREAD

**Issue by XVilka** [falconre/falcon#79]
Would make development easier since many operations are already implemented out of the box

- https://github.com/petgraph/petgraph
- https://docs.rs/petgraph
- https://crates.io/crates/petgraph

**Comment by endeav0r** [comment]
I like our current graph implementation, and don’t see a strong reason to change it :(.

I’ll leave this open for a few weeks for counter-points, but I think Falcon’s graph implementation is here to stay.
